#! /bin/sh
# This file is a part of DevkitPro
#   http://sourceforge.net/projects/devkitpro
# File: alignbin
# aligns a file to a multiple of 4bytes in length

if [ $# -ne 1 ]
then
    echo "Usage: $0 <filename>"
    echo "       aligns file length to multiple of 4 bytes"
    exit 1
fi

if [ -d $1 ]
then
	echo "File not found"
	exit 1
fi

echo -n $(( `cat $1 | wc -c` & 3 )) | sed -e 's/0//g' | sed -e 's/1/XXX/g' | sed -e 's/2/XX/g' | sed -e 's/3/X/g' >> $1